[project]
name = "orcaia-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn[standard]==0.30.0",
  "pydantic==2.8.2",
  "SQLAlchemy==2.0.35",
  "psycopg[binary]==3.2.1",
  "python-dotenv==1.0.1"
]